# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20170627_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymap',
            name='topojson',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='countrymap',
            name='geojson',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
