# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20170628_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymap',
            name='country_represented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_maps', to='maps.Country'),
        ),
    ]
